title: Monte Carlo Neutron Transport
description: Educational Monte Carlo code for neutron transport simulation
theme: jekyll-theme-cayman

# GitHub metadata
repository: ybadr16/PYNEUT
# plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index

# Enable relative links
relative_links:
  enabled: true
  collections: false

# Enable README index
readme_index:
  enabled: true

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules